### ISSUE TITLE
 use {@link ReactHorizontalScrollView}.

### ISSUE THREAD

**Issue by ignivadeep** [mohtada-h/react-native-nested-scrollview#1]
Unable to understand how should i use it for nested horizontal scroll.

**Comment by smallpath** [comment]
Hi, you can wrap it easily and the last thing is to specific the height of inner view. example code [here](https://github.com/smallpath/psnine/blob/master/psnine/container/user/UserTab.js#L72) and it looks like:

![img](https://oebegwmfv.qnssl.com/20170718/143834_ezgif.com-crop.gif)

**Comment by ignivadeep** [comment]
Hi... 
![screenshot_1500362705](https://user-images.githubusercontent.com/22214968/28305308-d0286bf2-6bb8-11e7-8879-f1f5b36cf839.png)

Problem : I have a horizontal scroll view. Inside that I need another  horizontal scroll view. But the child  horizontal scroll view is not working.
I also tried above solution but without luck.

Thanks for help

**Comment by smallpath** [comment]
Hi, I think you misunderstand the NestedScrollView in Android. NestedScrollView is introduced to handle nested situation for meterial design component such as CollapseToolbar as shown above, not for nested scroll views in the save directions.

Maybe you can consider to change one of your scrollview into vertical directions

**Comment by ignivadeep** [comment]
Hi, 
Thanks for help and quick response. I think its for nested scroll view in same direction.
Please can you suggest any solutions for above problem.
